PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
CONSTRUCT {
?uri2 a owl:Class;
    rdfs:subClassOf ?subClassOf2 .

?method2 rdfs:subClassOf ?uri2 .


}
WHERE {

{ ?uri a owl:Class . }
UNION
{ ?uri a owl:Ontology . }

OPTIONAL { ?uri rdfs:subClassOf ?subClassOf . }
?method cov:methodOf ?uri .


BIND ( iri(
    replace(
        replace(str(?uri), "(.*\\:.*?)\\:(.*)", "$1_$2"),
        "http://www.cropontology.org/rdf/",
        "http://purl.obolibrary.org/obo/"
    )
) AS ?uri2 )
BIND ( iri(
    replace(
        replace(str(?subClassOf), "(.*\\:.*?)\\:(.*)", "$1_$2"),
        "http://www.cropontology.org/rdf/",
        "http://purl.obolibrary.org/obo/"
    )
) AS ?subClassOf2 )
BIND ( str(
    replace(
        replace(str(?method), "(.*\\:.*?)\\:(.*)", "$1_$2"),
        "http://www.cropontology.org/rdf/",
        "http://purl.obolibrary.org/obo/"
    )
) AS ?method2 )
BIND ( str(
    replace(
        replace(str(?scale), "(.*\\:.*?)\\:(.*)", "$1_$2"),
        "http://www.cropontology.org/rdf/",
        "http://purl.obolibrary.org/obo/"
    )
) AS ?scale2 )
}
