"""create OntologyManageAccess table

Revision ID: 1f5f6eb9efbe
Revises: bca59e172b1e
Create Date: 2023-10-31 04:54:22.076634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5f6eb9efbe'
down_revision = 'bca59e172b1e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontologymanageaccess',
    sa.Column('ontology_manage_access_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Unicode(length=120), nullable=False),
    sa.Column('ontology_id', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_ontologymanageaccess_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ontology_manage_access_id', name=op.f('pk_ontologymanageaccess'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ontologymanageaccess')
    # ### end Alembic commands ###
