"""Add table of usersections

Revision ID: 2756f31b4667
Revises: a8b744b5b3d4
Create Date: 2021-06-16 11:43:39.123085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2756f31b4667"
down_revision = "a8b744b5b3d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usersection",
        sa.Column("user_id", sa.Unicode(length=120), nullable=False),
        sa.Column("section_id", sa.Unicode(length=120), nullable=False),
        sa.Column("access_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["section.section_id"],
            name=op.f("fk_usersection_section_id_section"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_usersection_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "section_id", name=op.f("pk_usersection")),
    )
    op.create_index(
        op.f("ix_usersection_section_id"), "usersection", ["section_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usersection_section_id"), table_name="usersection")
    op.drop_table("usersection")
    # ### end Alembic commands ###
