"""Added account table

Revision ID: bca59e172b1e
Revises: 2756f31b4667
Create Date: 2023-09-09 22:29:49.694482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca59e172b1e'
down_revision = '2756f31b4667'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_password_reset_expires_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('user_password_reset_key', sa.Unicode(length=64), nullable=True))
    op.add_column('user', sa.Column('user_password_reset_token', sa.Unicode(length=64), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_password_reset_token')
    op.drop_column('user', 'user_password_reset_key')
    op.drop_column('user', 'user_password_reset_expires_on')
    # ### end Alembic commands ###
