"""New tables: page, section and menu

Revision ID: c9caceaff343
Revises: 9147a676fbff
Create Date: 2020-09-10 16:20:39.494826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9caceaff343"
down_revision = "9147a676fbff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu",
        sa.Column("menu_id", sa.Unicode(length=120), nullable=False),
        sa.Column("menu_desc", sa.Unicode(length=120), nullable=True),
        sa.Column(
            "menu_fixed", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
        sa.Column("menu_content", sa.UnicodeText(), nullable=True),
        sa.Column("extras", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("menu_id", name=op.f("pk_menu")),
    )
    op.create_table(
        "page",
        sa.Column("page_id", sa.Unicode(length=120), nullable=False),
        sa.Column("page_desc", sa.Unicode(length=120), nullable=True),
        sa.Column(
            "page_fixed", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
        sa.Column("page_content", sa.UnicodeText(), nullable=True),
        sa.Column("extras", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("page_id", name=op.f("pk_page")),
    )
    op.create_table(
        "section",
        sa.Column("section_id", sa.Unicode(length=120), nullable=False),
        sa.Column("section_desc", sa.Unicode(length=120), nullable=True),
        sa.Column(
            "section_fixed", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
        sa.Column("section_content", sa.UnicodeText(), nullable=True),
        sa.Column("extras", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("section_id", name=op.f("pk_section")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("section")
    op.drop_table("page")
    op.drop_table("menu")
    # ### end Alembic commands ###
