"""Add page last update

Revision ID: ee885074f87a
Revises: c9caceaff343
Create Date: 2020-09-14 12:56:38.584218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee885074f87a"
down_revision = "c9caceaff343"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page", sa.Column("page_lastupdate", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page", "page_lastupdate")
    # ### end Alembic commands ###
